project:
  type: website
  render:
    - index.qmd
    - pxrf.qmd
    - shape.qmd

website:
  margin-header: |
    ![](/img/slab.png)
  navbar:
    logo: "sfasu.png"
    left:
      - href: index.qmd
        text: Home
      - pxrf.qmd
      - shape.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

