project:
  type: website

website:
  title: "gahaganmorph.5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - pxrf.qmd
      - shape.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

