project:
  type: website
  render:
    - index.qmd
    - color.qmd
    - pxrf-color.qmd
    - shape.qmd

website:
  margin-header: |
    ![](/img/slab.png)
  navbar:
    logo: "sfasu.png"
    right:
      - href: index.qmd
        text: Home
      - color.qmd
      - pxrf-color.qmd
      - shape.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
