---
title: "RMCG and Geochemistry"
---

```{r read}
## load packages
library(here)
library(tidyverse)
library(tidyr)
library(vegan)
library(ggpubr)
library(ggfortify)
library(cluster)
library(ggExtra)
library(ggConvexHull)
library(wesanderson)

## load pXRF + categorical.data----
pxrf <- read.csv('pxrf.csv',
                 header = TRUE,
                 as.is = TRUE)

cat <- read.csv('catdata.csv',
                header = TRUE,
                as.is = TRUE)

# join categorical + pxrf data sans 611
cat.pxrf <- left_join(cat, pxrf, by = "X") %>% 
  filter(X != '611')

#palette
pal <- wes_palette("Moonrise2")
```

## Principal Components Analysis

```{r pca}
#pca
df <- data.frame(cat.pxrf[,c(7:13)])
pch.gps <- c(15,18)[as.factor(cat.pxrf$ColorGroup)]
ColorGroup <- cat.pxrf$ColorGroup

## pca plot using correlation matrix
pca <- autoplot(prcomp(df, scale. = TRUE),
                data = cat.pxrf,
                asp = 1,
                shape = pch.gps,
                colour = "ColorGroup",
                loadings = TRUE, 
                loadings.colour = 'blue',
                loadings.label = TRUE,
                loadings.label.size = 3,
                frame = TRUE) +
  geom_convexhull(alpha = 0.1, aes(fill = ColorGroup)) +
  scale_fill_manual(values = pal) +
  scale_colour_manual(values = pal)

ggMarginal(pca, groupColour = TRUE)
```

```{r permanova general}
# perMANOVA
gahagan.matrix <- as.matrix(df) # response vars
gahagan.mat <- sqrt(gahagan.matrix) # sqrt transform
gahagan.dist <- vegdist(gahagan.mat,
                        method = 'bray') # dissimilarity matrix
set.seed(10) # make results reproducible

# model: gahagan cat.pxrf material as a function of ColorGroup
gahagan <- adonis2(gahagan.dist ~ ColorGroup,
                   data = cat.pxrf,
                   permutations = 10000,
                   method = 'bray')

## does raw material geochemistry differ by ColorGroup?
gahagan
```
