---
title: "Elemental"
---

```{r read}
## load packages
library(here)
library(tidyverse)
library(vegan)
library(ggpubr)
library(ggfortify)
library(cluster)
library(ggExtra)
library(ggConvexHull)
library(wesanderson)

## load pXRF + qual.data----
raw <- read.csv('pxrf1.csv',
                header = TRUE,
                as.is = TRUE)

#palette
pal <- wes_palette("Moonrise2")
```

## Quantitative attributes by sex

```{r boxplotlin, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# boxplot of Al.K12 by site
Al.K12 <- ggplot(raw, aes(x = Site, y = Al.K12, color = Site)) +
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',stackdir = 'center', dotsize = 0.3) +
  scale_colour_manual(values = pal) +
  theme(legend.position = 'none') +
  labs(x = 'Site', 
       y = 'Al.K12')

# boxplot of Ba.L1 by site
Ba.L1 <- ggplot(raw, aes(x = Site, y = Ba.L1, color = Site)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',stackdir = 'center', dotsize = 0.3) +
  scale_colour_manual(values = pal) +
  theme(legend.position = 'none') +
  labs(x = 'Site', 
       y = 'Ba.L1')

# boxplot of Ca.K12 by site
Ca.K12 <- ggplot(raw, aes(x = Site, y = Ca.K12, color = Site)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',stackdir = 'center', dotsize = 0.3) +
  scale_colour_manual(values = pal) +
  theme(legend.position = 'none') +
  labs(x = 'Site',
       y = 'Ca.K12')

# boxplot of Fe.K12
Fe.K12 <- ggplot(raw, aes(x = Site, y = Fe.K12, color = Site)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',stackdir = 'center', dotsize = 0.3) +
  scale_colour_manual(values = pal) +
  theme(legend.position = 'none') +
  labs(x = 'Site', 
       y = 'Fe.K12')

# boxplot of Ni.K12
Ni.K12 <- ggplot(raw, aes(x = Site, y = Ni.K12, color = Site)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',stackdir = 'center', dotsize = 0.3) +
  scale_colour_manual(values = pal) +
  theme(legend.position = 'none') +
  labs(x = 'Site', 
       y = 'Ni.K12')

# boxplot of Sn.K12
Sn.K12 <- ggplot(raw, aes(x = Site, y = Sn.K12, color = Site)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',stackdir = 'center', dotsize = 0.3) +
  scale_colour_manual(values = pal) +
  theme(legend.position = 'none') +
  labs(x = 'Site', 
       y = 'Sn.K12')

# boxplot of Sn.L1
Sn.L1 <- ggplot(raw, aes(x = Site, y = Sn.L1, color = Site)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',stackdir = 'center', dotsize = 0.3) +
  scale_colour_manual(values = pal) +
  theme(legend.position = 'none') +
  labs(x = 'Site', 
       y = 'Sn.L1')

# boxplot of Zn.K12
Zn.K12 <- ggplot(raw, aes(x = Site, y = Zn.K12, color = Site)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',stackdir = 'center', dotsize = 0.3) +
  scale_colour_manual(values = pal) +
  theme(legend.position = 'none') +
  labs(x = 'Site', 
       y = 'Zn.K12')

# figure layout
pxrf.figure <- ggarrange(Al.K12, Ba.L1, Ca.K12, Fe.K12, Ni.K12, 
                         Sn.K12, Sn.L1, Zn.K12,
                  labels = c('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'),
                  ncol = 4, nrow = 2)
              
## plot figure
pxrf.figure
```

```{r pca}
#pca
pch.gps <- c(15,17)[as.factor(raw$Site)]
Site <- raw$Site

## pca plot using correlation matrix
pca <- autoplot(prcomp(raw[,c(4:5,8:11)], scale. = TRUE),
                data = raw,
                asp = 1,
                shape = pch.gps,
                colour = "Site",
                loadings = TRUE, 
                loadings.colour = 'blue',
                loadings.label = TRUE,
                loadings.label.size = 3,
                frame = TRUE) +
  geom_convexhull(alpha = 0.1, aes(fill = Site)) +
  scale_fill_manual(values = pal) +
  scale_colour_manual(values = pal)

ggMarginal(pca, groupColour = TRUE)
```

```{r permanova}
# perMANOVA
gahagan.matrix <- as.matrix(raw[,c(4:5, 8:11)]) # response vars
gahagan.mat <- sqrt(gahagan.matrix) # sqrt transform
gahagan.dist <- vegdist(gahagan.mat,
                        method = 'bray') # dissimilarity matrix
set.seed(10) # make results reproducible

# model: gahagan raw material as a function of site
gahagan <- adonis2(gahagan.dist ~ Site,
                   data = raw,
                   permutations = 10000,
                   method = 'bray')

## does raw material differ by site?
gahagan
```
