---
title: |
  Diagnostic biface acquisition through trade with distinct extralocal communities of practice: A case study from the American Southeast
type: ORIGINAL RESEARCH ARTICLE
author:
  - name: Robert Z. Selden, Jr.
    affil: a
    email: zselden@sfasu.edu
  - name: Catherine G. Cooper
    affil: b
  - name: John E. Dockall
    affil: c
affiliation:
  - num: a
    address: |
      Heritage Research Center, Stephen F. Austin State University; Department of Biology, Stephen F. Austin State University; Texas Archeological Research Laboratory, The University of Texas at Austin; and Cultural Heritage Department, Jean Monnet University
  - num: b
    address: |
      National Center for Preservation Technology and Training, National Park Service
  - num: c
    address: |
      Stantec, Inc.
bibliography: article.bib
abstract: |
  Nodule size and mechanical flaking properties have been advanced to account for assemblage level differences in the morphology of stone tools within regions where raw material is abundant. However, in instances where lithic raw materials---larger nodules in particular---were scarce, did traders interact with brokers from distinct extralocal communities to acquire large bifaces? Gahagan bifaces are among those implements diagnostic of Formative/Early Caddo material culture (CE 800 - 1250); although, due to a lack of local production evidence, it is also widely accepted that Gahagan bifaces were not manufactured by the Caddo. This study asks whether Caddo traders engaged in commerce with brokers from discrete extralocal communities of practice to acquire Gahagan bifaces. Results demonstrate significant differences in Gahagan biface geochemistry and shape based on color group assignment, suggesting that Gahagan biface shape was conditioned by raw material color. Given these findings, it is posited that Caddo traders acquired Gahagan bifaces from two distinct communities of practice, where local raw material and production differences resulted in Gahagan bifaces that were unique in color, geochemistry, and shape.
keywords: |
  American Southeast; Caddo; NAGPRA; lithics; raw material color; pXRF; computational archaeology; museum studies; digital humanities; non-Western art history; STEM; STEAM
header-includes: |
  \usepackage{hyperref}
  \usepackage[utf8]{inputenc}
  \def\tightlist{}
output: rticles::tf_article
---

> “The question of questions for mankind—the problem which underlies all others, and is more deeply interesting than any other—is the ascertainment of the place which man occupies in nature, and of his relation to the universe of things.” **–H. Thomas Henry Huxley**, _Man’s Place in Nature_

# Introduction



# Methods and Results



# Discussion and Conclusion



# Acknowledgement(s) {-}

We extend our gratitude to the Caddo Nation of Oklahoma, the Caddo Nation Tribal Council, Tribal Chairman, and Tribal Historic Preservation Office for their continued guidance and support of our work, as well as access to NAGPRA and previously repatriated collections. Thanks also to the Williamson Museum and the Louisiana State Exhibit Museum for providing access to the Gahagan bifaces, and to Bruce Kayser for his time and guidance with pXRF questions. RZS also extends his gratitude to Emma Sherratt, Kersten Bergstrom, Lauren Butaric, Dean C. Adams, and Michael L. Collyer for their constructive criticisms and suggestions throughout the development of this research program.

# Disclosure statement {-}

The authors declare no conflicts of interest.

# Data management {-}

All data and analysis code associated with this project are openly available through the [GitHub](https://github.com/seldenlab/gahaganmorph.5) repository, which is digitally curated on the Open Science Framework ([DOI 10.17605/OSF.IO/3JB94](https://osf.io/3jb94/)). Additionally, images of all Gahagan bifaces used in this study are openly available to view/download through an open access comparative collection ([https://scholarworks.sfasu.edu/ita-gahaganbiface/](https://scholarworks.sfasu.edu/ita-gahaganbiface/)). The supplementary materials include all analysis data and code used in the study, providing a means for others to reproduce (exactly) those results discussed and expounded upon in this article. The replicable nature of this undertaking provides others with the means to critically assess and evaluate the various analytical components of this study [@RN20915;@RN20916;@RN20917], which is a necessary requirement for the production of reliable knowledge. 

Reproducibility projects in [psychology](https://osf.io/ezcuj/) and [cancer biology](https://www.cos.io/rpcb) are impacting current research practices across all domains. Examples of reproducible research are becoming more abundant in archaeology [@RN20804;@RN21009;@RN21001;@RN9364;@RN11097], and the next generation of archaeologists are learning those tools and methods needed to reproduce and/or replicate research results [@RN21007]. Reproducible and replicable research work flows are often employed at the highest levels of humanities-based inquiries to mitigate concern or doubt regarding proper execution, and is of particular import should the results have—explicitly or implicitly—a major impact on scientific progress [@RN21008].

# Funding {-}

Components of the analytical workflow were developed and funded by a Preservation Technology and Training grant (P14AP00138) to RZS from the National Center for Preservation Technology and Training, as well as grants to RZS from the Caddo Nation of Oklahoma, National Forests and Grasslands in Texas (15-PA-11081300-033) and the United States Forest Service (20-PA-11081300-074). Additional funding and logistical support was provided by the Heritage Research Center at Stephen F. Austin State University and the National Center for Preservation Technology and Training.

# References
